### ISSUE TITLE
Drupal 8.7 Composer install issue

### ISSUE THREAD

**Issue by bladeaweb** [integratedexperts/ci-builder#14]
I tried your ci-builder. It's almost awesome, but. 
https://drive.google.com/file/d/1Dy_pg4r_Kfu3_v1nFXTjDw5dV2AoUuNS/view?usp=sharing

**Comment by alexdesignworks** [comment]
This is not Drupal image. It is an image for starting containers that would use drupal image. It is a runner - it does not have anything required for Drupal. You need to use other images.

Check out drupal-dev.io - it has everything required.
